batch_size: 64
lr_scheduler: cosine
cosine_scheduler_config:
  lr_decay_steps: 100000000.0
  min_lr: 1.0e-05
  warmup_steps: 1000
StepLR_scheduler_config:
  gamma: 0.1
  step_size: 1000
learning_rate: 0.001
max_epochs: 100
optimizer: AdamW
use_wandb: true
wandb_config:
  wandb_project: composition_v1
  wandb_entity: scgpt-siyu
weight_decay: 0.01
seed: 42
num_workers: 4
use_loss_n: true
